SELECT 
TMP.COD_LOJA, TMP.LOJA,  TMP.COD_PARCEIRO, TMP.PARCEIRO, TMP.COD_CFOP, TMP.CFOP,
TMP.NF,  TMP.SERIE, TMP.DOC_RECEBER, TMP.EMISSAO, TMP.VENCIMENTO, 
CASE
   WHEN func_top = 'A' THEN TMP.VALOR_PARCELA
   ELSE TMP.VALOR_PARCELA * -1
END   
VALOR_PARCELA, 
TMP.COD_COND_PAGAMENTO, TMP.COND_PAGAMENTO, 
CASE
   WHEN func_top = 'A' THEN VALOR_DOCUMENTO
   ELSE VALOR_DOCUMENTO * -1
END VALOR_DOCUMENTO, TMP.CHAVE,  VENC_ORIGINAL VENCIMENTO_ORIGINAL
FROM 
(
select 
NTA.CODI_EMP COD_LOJA, EMP.IDEN_EMP LOJA,  TRA.CODI_TRA COD_PARCEIRO, TRA.RAZA_TRA PARCEIRO, CFO.CCFO_CFO COD_CFOP, CFO.DESC_CFO CFOP,
NTA.NOTA_NOT NF, NTA.SERI_NOT SERIE, NOC.nume_cbr DOC_RECEBER, NTA.DEMI_NOT EMISSAO, NOC.VENC_rEC VENCIMENTO, 
NOC.VLOR_REC VALOR_PARCELA, 
CON.COND_CON COD_COND_PAGAMENTO, CON.DESC_CON COND_PAGAMENTO, 
NOC.tota_cbr VALOR_DOCUMENTO, '#'|| NTA.CHAV_NOT CHAVE, f.func_top, NOC.CTRL_CBR
from nota nta 
INNER JOIN CADEMP EMP ON EMP.CODI_EMP = NTA.CODI_EMP
INNER JOIN FUNCAOTOPER F ON (F.CODI_TOP = NTA.CODI_TOP)
INNER JOIN TRANSAC TRA ON TRA.CODI_TRA = NTA.CODI_TRA
INNER JOIN CFO ON CFO.CCFO_CFO = NTA.CCFO_CFO
LEFT JOIN CONDICAO CON ON CON.COND_CON = NTA.COND_CON
left join 
(
SELECT 
   noc.codi_tra, noc.sdoc_noc, noc.ndoc_noc, NOC.CODI_EMP,
   cbr.nume_cbr, REC.VENC_rEC, REC.VLOR_REC, cbr.tota_cbr,
   NOC.CTRL_CBR
FROM notacrc noc                        
INNER JOIN CABREC CBR ON CBR.CTRL_CBR = NOC.CTRL_CBR AND
                        CBR.SITU_CBR <> 'C'
INNER JOIN RECEBER REC ON REC.CTRL_CBR = CBR.CTRL_CBR AND
                         REC.SITU_REC <> 'C' 
WHERE noc.tdoc_noc = 'NE'   
) NOC ON NOC.CODI_EMP = NTA.CODI_EMP AND
         NOC.NDOC_NOC = NTA.NOTA_NOT AND
         NOC.SDOC_NOC = NTA.SERI_NOT AND
         NOC.CODI_TRA = NTA.CODI_TRA
WHERE NTA.SITU_NOT <> '9' AND F.CODI_PTO = 102
AND NTA.DEMI_NOT BETWEEN '01.01.1900' AND '31/12/2090'
UNION 
select 
NTA.CODI_EMP COD_LOJA, EMP.IDEN_EMP LOJA,  TRA.CODI_TRA COD_PARCEIRO, TRA.RAZA_TRA PARCEIRO, CFO.CCFO_CFO COD_CFOP, CFO.DESC_CFO CFOP,
NTA.NUME_NFE NF, NTA.SERI_NFE SERIE, NOC.nume_cbr DOC_RECEBER, NTA.DREC_NFE EMISSAO, NOC.VENC_rEC VENCIMENTO, 
NOC.VLOR_REC VALOR_PARCELA, 
CON.COND_CON COD_COND_PAGAMENTO, CON.DESC_CON COND_PAGAMENTO, 
NOC.tota_cbr VALOR_DOCUMENTO,'#'|| NTA.CHAV_NFE CHAVE, f.func_top, NOC.CTRL_CBR
from NFENTRA nta 
INNER JOIN CADEMP EMP ON EMP.CODI_EMP = NTA.CODI_EMP
INNER JOIN FUNCAOTOPER F ON (F.CODI_TOP = NTA.CODI_TOP)
INNER JOIN TRANSAC TRA ON TRA.CODI_TRA = NTA.CODI_TRA
INNER JOIN CFO ON CFO.CCFO_CFO = NTA.CCFO_CFO
LEFT JOIN CONDICAO CON ON CON.COND_CON = NTA.COND_CON
left join 
(
SELECT 
   noc.codi_tra, noc.sdoc_noc, noc.ndoc_noc, NOC.CODI_EMP,
   cbr.nume_cbr, REC.VENC_rEC, REC.VLOR_REC, cbr.tota_cbr,
   CBR.CTRL_CBR
FROM notacrc noc                        
INNER JOIN CABREC CBR ON CBR.CTRL_CBR = NOC.CTRL_CBR AND
                        CBR.SITU_CBR <> 'C'
INNER JOIN RECEBER REC ON REC.CTRL_CBR = CBR.CTRL_CBR AND
                         REC.SITU_REC <> 'C' 
WHERE noc.tdoc_noc = 'NT'   
) NOC ON NOC.CODI_EMP = NTA.CODI_EMP AND
         NOC.NDOC_NOC = NTA.NUME_NFE AND
         NOC.SDOC_NOC = NTA.SERI_NFE AND
         NOC.CODI_TRA = NTA.CODI_TRA
WHERE  F.CODI_PTO = 102
AND NTA.DREC_NFE BETWEEN '01.01.1900' AND '31/12/2090'
UNION ALL 
    SELECT     
    N.CODI_EMP COD_LOJA, EMP.IDEN_EMP LOJA,  TRA.CODI_TRA COD_PARCEIRO, TRA.RAZA_TRA PARCEIRO,  NULL COD_CFOP, NULL CFOP,
    CDS.CODI_CDS NF, 'DZ' SERIE, NOC.nume_cbr DOC_RECEBER, CDS.DATA_CDS EMISSAO, NOC.VENC_rEC VENCIMENTO,     
    NOC.VLOR_REC VALOR_PARCELA, 
    CON.COND_CON COD_COND_PAGAMENTO, CON.DESC_CON COND_PAGAMENTO, 
    NOC.tota_cbr VALOR_DOCUMENTO, NULL CHAVE,  f.func_top, NOC.CTRL_CBR                
    FROM DOCDESFAZ DDZ    
    JOIN 
       CABDESFAZ CDS  ON (CDS.CODI_EMP  = DDZ.CODI_EMP)
                     AND (CDS.CODI_CDS = DDZ.CODI_CDS)
    JOIN 
       TIPOOPER TOP ON (CDS.CODI_TOP = TOP.CODI_TOP)
    INNER JOIN 
       FUNCAOTOPER F  ON (F.CODI_TOP = TOP.CODI_TOP)   
    JOIN 
       TRANSAC TRA ON (TRA.CODI_TRA = CDS.CODI_TRA)
    JOIN 
       NOTA N  ON (N.CODI_EMP  = DDZ.CODI_EMP)
              AND (N.NOTA_NOT = DDZ.NDOC_DDZ)
              AND (N.SERI_NOT = DDZ.SERI_DDZ)
              AND (N.CODI_TRA = DDZ.CODI_TRA)
    JOIN 
       CADEMP EMP ON EMP.CODI_EMP = N.CODI_EMP 
    LEFT JOIN 
    (    
    SELECT 
        noc.codi_tra, noc.sdoc_noc, noc.ndoc_noc, NOC.CODI_EMP,
        cbr.nume_cbr, REC.VENC_rEC, REC.VLOR_REC, cbr.tota_cbr,
        CBR.CTRL_CBR
     FROM 
        notacrc noc                        
     INNER JOIN 
        CABREC CBR ON CBR.CTRL_CBR = NOC.CTRL_CBR AND
                      CBR.SITU_CBR <> 'C'
     INNER JOIN RECEBER REC ON REC.CTRL_CBR = CBR.CTRL_CBR AND
                               REC.SITU_REC <> 'C' 
    WHERE noc.tdoc_noc = 'DZ' 
    )NOC ON CDS.CODI_CDS = NOC.NDOC_NOC AND
            CDS.CODI_TRA = NOC.CODI_TRA  
    LEFT JOIN condicao con ON con.COND_CON = n.COND_CON
        
    WHERE (DDZ.TIPO_DDZ = 'NE') AND
     F.CODI_PTO = 102 AND CDS.DATA_CDS BETWEEN '01.01.1900' AND '31/12/2090'   
    UNION ALL
    SELECT     
    N.CODI_EMP COD_LOJA, EMP.IDEN_EMP LOJA,  TRA.CODI_TRA COD_PARCEIRO, TRA.RAZA_TRA PARCEIRO,  NULL COD_CFOP, NULL CFOP,
    CDS.CODI_CDS NF, 'DZ' SERIE, NOC.nume_cbr DOC_RECEBER, CDS.DATA_CDS EMISSAO, NOC.VENC_rEC VENCIMENTO,     
    NOC.VLOR_REC VALOR_PARCELA, 
    CON.COND_CON COD_COND_PAGAMENTO, CON.DESC_CON COND_PAGAMENTO, 
    NOC.tota_cbr VALOR_DOCUMENTO, NULL CHAVE, f.func_top, NOC.CTRL_CBR                
    FROM DOCDESFAZ DDZ    
    JOIN 
       CABDESFAZ CDS  ON (CDS.CODI_EMP  = DDZ.CODI_EMP)
                     AND (CDS.CODI_CDS = DDZ.CODI_CDS)
    JOIN 
       TIPOOPER TOP ON (CDS.CODI_TOP = TOP.CODI_TOP)
    INNER JOIN 
       FUNCAOTOPER F  ON (F.CODI_TOP = TOP.CODI_TOP)   
    JOIN 
       TRANSAC TRA ON (TRA.CODI_TRA = CDS.CODI_TRA)
    JOIN 
       NFENTRA N  ON (N.CODI_EMP  = DDZ.CODI_EMP)
                 AND (N.CODI_TRA = DDZ.CODI_TRA)
                 AND (N.NUME_NFE = DDZ.NDOC_DDZ)
                 AND (N.SERI_NFE = DDZ.SERI_DDZ)
    JOIN 
       CADEMP EMP ON EMP.CODI_EMP = N.CODI_EMP  
    LEFT JOIN 
    (    
    SELECT 
        noc.codi_tra, noc.sdoc_noc, noc.ndoc_noc, NOC.CODI_EMP,
        cbr.nume_cbr, REC.VENC_rEC, REC.VLOR_REC, cbr.tota_cbr,
        CBR.CTRL_CBR
     FROM 
        notacrc noc                        
     INNER JOIN 
        CABREC CBR ON CBR.CTRL_CBR = NOC.CTRL_CBR AND
                      CBR.SITU_CBR <> 'C'
     INNER JOIN RECEBER REC ON REC.CTRL_CBR = CBR.CTRL_CBR AND
                               REC.SITU_REC <> 'C' 
    WHERE noc.tdoc_noc = 'DZ' 
    )NOC ON CDS.CODI_CDS = NOC.NDOC_NOC AND
            CDS.CODI_TRA = NOC.CODI_TRA 
    LEFT JOIN condicao con ON con.COND_CON = n.COND_CON        
    WHERE (DDZ.TIPO_DDZ = 'NT') AND
     F.CODI_PTO = 102 AND CDS.DATA_CDS BETWEEN '01.01.1900' AND '31/12/2090'
) TMP 
LEFT JOIN 
(
select
CR.CTRL_CBR, min(RC.VENC_RRN) VENC_ORIGINAL
from CABREC CR 
INNER JOIN RNCCABREC R ON R.CTRL_CBR = CR.CTRL_CBR
INNER JOIN RNCRECEBER RC ON RC.CTRL_CNR = R.CTRL_CNR
group by
CR.CTRL_CBR
) CBR ON  TMP.CTRL_CBR = CBR.CTRL_CBR WHERE TMP.EMISSAO BETWEEN '01.01.2025' AND '31.12.2070'